---
- hosts: opteamwindowsservers 
  gather_facts: True
  tasks:
  - name: Get all processes from windows host
    win_shell: Get-Process | ConvertTo-Json
    register: result
  - name: Print the previous commmand output
    debug:
      var: result.stdout
