---
- hosts: opteamwindowsservers 
  gather_facts: True
  tasks:
  - name: Run a pwsh command
    win_shell: Get-Process | ConvertTo-Json
    register: result
  - name: Print the previous commmand output
    debug:
      var: result
